# Generated by Django 5.1.6 on 2025-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_alter_book_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='booklist.genre'),
        ),
    ]
